server:
  port: 8086
  servlet:
    contextPath: /talkyo
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  resources:
    static-locations: file:/Users/chenyifan/Documents/workspace-fan/talkyo/src/main/resources/static/
  data:
    mongodb:
      uri: mongodb://localhost:27017
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8086/talkyo/login/oauth2/code/google
            client-id: ${google-client-id}
            client-secret: ${google-client-secret}
            scope:
              - email
              - profile
          line:
            client-id: ${line-client-id}
            client-secret: ${line-client-secret}
            redirect-uri: http://localhost:8086/talkyo/callback
            scope:
              - openid
              - profile
            authorization-grant-type: authorization_code
        provider:
          line:
            authorization-uri: https://access.line.me/oauth2/v2.1/authorize
            token-uri: https://api.line.me/oauth2/v2.1/token
            user-info-uri: https://api.line.me/v2/profile
            user-name-attribute: userId

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

azure:
  ai:
    audio:
      key: ${azure-audio-api-key}
      region: ${azure-audio-region}
    text:
      analytics:
        key: ${azure-text-analytics-api-key}
      endpoint: ${azure-text-analytics-endpoint}

config:
  globalDomain: http://localhost:8086/talkyo/
  audioSavePath: /Users/chenyifan/Documents/workspace-fan/talkyo/audio/
  picSavePath: /Users/chenyifan/Documents/workspace-fan/talkyo/image/
  picShowPath: http://localhost:8086/talkyo/image/
  audioShowPath: http://localhost:8086/talkyo/audio/
  jsonPath: /Users/chenyifan/Documents/workspace-fan/talkyo/src/main/resources/static/js/
  openaiApiKey: ${openai-api-key}
  geminiApiKey: ${gemini-api-key}
  cloudTranslateApiKey: ${cloud-translate-api-key}