server:
  port: 8086
  servlet:
    contextPath: /talkyo
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  resources:
    static-locations: file:/Users/chenyifan/Documents/workspace-fan/talkyo/src/main/resources/static/
  data:
    mongodb:
      uri: mongodb://localhost:27017
  rabbitmq:
    host: localhost
    port: 5672
    username: ${db-username}
    password: ${db-password}
    listener:
      simple:
        prefetch: 1 #當多個消費者訂閱同一個Queue時，確保每個消費者最多處理一條Msg，而不是某些消費者堆積大量消息。
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 1000ms
          multiplier: 1
          max-attempts: 1
          stateless: true
    connection-timeout: 1s
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        multiplier: 1
        max-attempts: 3
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8086/talkyo/login/oauth2/code/google
            client-id: ${google-client-id}
            client-secret: ${google-client-secret}
            scope:
              - email
              - profile
          line:
            client-id: ${line-client-id}
            client-secret: ${line-client-secret}
            redirect-uri: http://localhost:8086/talkyo/callback
            scope:
              - openid
              - profile
            authorization-grant-type: authorization_code
        provider:
          line:
            authorization-uri: https://access.line.me/oauth2/v2.1/authorize
            token-uri: https://api.line.me/oauth2/v2.1/token
            user-info-uri: https://api.line.me/v2/profile
            user-name-attribute: userId

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

azure:
  ai:
    audio:
      key: ${azure-audio-api-key}
      region: ${azure-audio-region}
    text:
      analytics:
        key: ${azure-text-analytics-api-key}
      endpoint: ${azure-text-analytics-endpoint}

gemini:
  ai:
    image:
      analytics:
        key: ${gemini-image-analytics-api-key}
      url: ${gemini-image-analytics-url}

config:
  globalDomain: http://localhost:8086/talkyo/
  audioSavePath: /Users/chenyifan/Documents/workspace-fan/talkyo/audio/
  picSavePath: /Users/chenyifan/Documents/workspace-fan/talkyo/image/
  picShowPath: http://localhost:8086/talkyo/image/
  audioShowPath: http://localhost:8086/talkyo/audio/
  jsonPath: /Users/chenyifan/Documents/workspace-fan/talkyo/src/main/resources/static/data/
  openaiApiKey: ${openai-api-key}
  cloudTranslateApiKey: ${cloud-translate-api-key}